### ISSUE TITLE
SyntaxError: invalid syntax on torch.load(root / f"models/{model_name}.pt", map_location=device)

### ISSUE THREAD

**Issue by khorshidisamira** [descriptinc/melgan-neurips#5]
Hello,
I have installed all requirements but when I run the following command, I am getting a syntax error, would you please help me?
>  python scripts/train.py --save_path logs/baseline --data_path audio/
Traceback (most recent call last):
  File "scripts/train.py", line 6, in <module>
    import mel2wav
  File "/home/sakhors/MelGan/melgan-neurips-master/mel2wav/__init__.py", line 1, in <module>
    from mel2wav.interface import load_model, MelVocoder
  File "/home/sakhors/MelGan/melgan-neurips-master/mel2wav/interface.py", line 43
    torch.load(root / f"models/{model_name}.pt", map_location=device)
                                              ^
SyntaxError: invalid syntax

>

**Comment by binarythinktank** [comment]
@khorshidisamira are you running it in python3?

**Comment by aidenjyoon** [comment]
Need to run in python 3.6 or higher.
